---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-spring-app
  annotations:
    deployment.kubernetes.io/revision: "revision-{{VERSION}}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-simple-spring-app
  template:
    metadata:
      labels:
        app: my-simple-spring-app
    spec:
      containers:
        - name: my-simple-spring-app
          image: 365185565134.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-simple-spring-app
spec:
  selector:
    app: my-simple-spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
